import React, {useState,useEffect} from 'react';
import { Loader, FormField,Card } from '../components';

const RenderCards=({data,title})=>{
  if(data?.length>0){
    return data.map((post) =>
  <Card key={post.id} {...post}> </Card>
)}

  return (
    <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>
        {title}
    </h2>
  )
  
}

const Home = () => {
    const [loading, setLoading] = useState(false);
    const [allPosts, setAllPosts]= useState(null);
    const [searchText, setSearchtext]= useState('');
  return (
    <section className='max-w-7xl mx-auto'>
        <div>
            <h1 className='font-extrabold text-[#2223328] text-[32px]'>
                The Community Showcase

            </h1>
            <p className='mt-2 text-[#666e75] text-[17px] max-w[500px]'>
                Browse through a collection of imaginative ans
                visually stunning images generated by PixelWiz.

            </p>
        </div>

        <div className='mt-16'>
            <FormField/>
        </div>

        <div className='mt-10'>
            {loading?(
                <div className='flex justify-center items-center'>
                    <Loader/>
                </div>
            ):(
                <>
                {searchText && (
                    <h2 className='font-medium text-[#666e75] text-xl mb-3'>
                        Showing results for <span className='text-[#222328'>
                            {searchText}
                        </span>
                    </h2>
                )}
                <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
                    {searchText ?(
                        <RenderCards data={[]}
                        title="No search results found"
                        ></RenderCards>
                    ):(
                    <RenderCards 
                    data={[]}
                    title="No posts found"
                    />)

                    }
                </div>
                </>
            )}
        </div>

    </section>
  )
}

export default Home