import React, {useState,useEffect} from 'react';
import { Loader, FormField,Card } from '../components';

const Home = () => {
    const [loading, setLoading] = useState(false);
    const [allPosts, setAllPosts]= useState(null);
    const [searchText, setSearchtext]= useState('abs');
  return (
    <section className='max-w-7xl mx-auto'>
        <div>
            <h1 className='font-extrabold text-[#2223328] text-[32px]'>
                The Community Showcase

            </h1>
            <p className='mt-2 text-[#666e75] text-[17px] max-w[500px]'>
                Browse through a collection of imaginative ans
                visually stunning images generated by PixelWiz.

            </p>
        </div>

        <div className='mt-16'>
            <FormField/>
        </div>

        <div className='mt-10'>
            {loading?(
                <div className='flex justify-center items-center'>
                    <Loader/>
                </div>
            ):(
                <>
                {searchText && (
                    <h2 className='font-medium text-[#666e75] text-xl mb-3'>
                        Showing results for 
                        <span className='text-[#222328'>
                            {searchText}
                        </span>
                    </h2>
                )}
                </>
            )}
        </div>

    </section>
  )
}

export default Home